### ISSUE TITLE
Update README?

### ISSUE THREAD

**Issue by a-hurst** [Katana-Steel/lithtech#12]
Hi there, I happened on this project a while back after hearing somewhere that the NOLF2 and Blood II source code got released, and I’ve been checking back every now and then ti see how the progress is going. It looks like you’ve accomplished a lot already, well done!

However, after reading over the project status part of the README with the updates and checklist, I noticed it’s been over a year since the README’s been updated and it looks like a lot of good work has been done since then (OpenGL renderer progress? SDL2 progress? Automated CI Linux builds with Travis? I can only infer from the latest commits), and I think it would be helpful for curious onlookers (like myself) and potential collaborators to have a README reflecting the recent achievements and current areas of work on the project.

Speaking of which, did you ever make any more progress on the model incompatibility issue? I’m curious if any of the earlier games compiled from source (e.g. Blood II) would load the commercial game resources just fine since the source was released after those games were. If you could get at least *one* commercial game running with this source port, I’m sure it would generate a lot of interest and support that could help keep it moving.

Thanks again for all your efforts!

**Comment by Katana-Steel** [comment]
Tons of good suggestions, thank you.

I've not been actively working for the past year.
I do have a pass/fail section on the Travis-CI build script, just don't know how to go about
extracting it and display it with markdown.

I'm only testing on linux as my main branch would suggest :D and at present without an
actual render on linux. 

Only @rohit-n has been testing the models from NOLF2.

As for SDL2, mainly input and window/rendering context, again mainly thanks to @rohit-n,
on the Linux build the main window is an SDL window.

**Comment by rohit-n** [comment]
I managed to get in game 2 years ago, but hit a stumbling block in the second mission (Siberia) when I was unable to use the lockpicking mechanic. Hopefully I (or someone else) can address the issue this time.

**Comment by Katana-Steel** [comment]
PR #15  was created with a few updates.
Consider this as an RFC. 
Anything specially that you'd like to see in the README ?

**Comment by a-hurst** [comment]
That looks good, glad to see people working on this again! My two main remaining suggestions would be to a) indicate the progress (if any) made on GPL assets vs retail game assets front, since it sounds like a major roadblock, and b) include a screenshot of the game running in some state with the current source code (if it's truly possible to get in-game at all, which @rohit-n 's  comment seems to suggest it is), preferably in windowed mode and on Linux if possible (i.e. showing easy visual evidence that it's the source port code running and not just the regular game in Windows, the animation for [the shockolate README](https://github.com/Interrupt/systemshock) is a nice example of this).

**Comment by Katana-Steel** [comment]
there's not game output running on Linux yet. The best I would be able to provide 
in way of a screenshot would be of NOFL2 initializing the game engine with a debugger,
close enough?

**Comment by a-hurst** [comment]
Yeah, that would work for the time being! Any visual indication of the project's working state would be great. A screenshot of the game running windowed on Windows would work as well.

What's remaining for getting anything in-game (even a menu or something) on Linux? Is the OpenGL render the hold-up, or is it the porting to SDL2? A little section on what's been accomplished so far with the 64-bit/Linux/OpenGL porting and what remains to be done would be good to add to the README too, in case anyone with the time and expertise to help out with some parts of the remaining work.

**Comment by rohit-n** [comment]
An OpenGL (or non-DX9) renderer is the big hold-up. SDL2 integration is mostly working, though there are a few areas that need conversion (the "say" menu that takes keyboard input isn't working).

I'd get started on the renderer, but I still want to play through a bit of the game before attempting it. For starters, the "decode" mechanic which is needed in the first mission isn't working, and I need to figure out why. If I can't even progress through the game as it is, there's no point in porting the renderer.
