### ISSUE TITLE
more source code

### ISSUE THREAD

**Issue by ArekReve** [Katana-Steel/lithtech#8]
Hey. Great work on that code.
Mayby it can help you. There is source code of Contract JACK game avilable 
https://www.mpgh.net/forum/showthread.php?t=759613

Regards.

**Comment by Katana-Steel** [comment]
Feel free to open a pull request and I'll see if I can merge it in... 

At present I'm more concerned with the code actually compile and run under linux

**Comment by MindrustUK** [comment]
Looks like there's some additional source for Blood II: The Chosen here;

https://github.com/videogamepreservation/blood2

Hope that's of some use.

**Comment by Katana-Steel** [comment]
@MindrustUK Blood2 source code was already added upstream
https://github.com/jsj2008/lithtech/tree/master/Blood2

thank you, I hope that satisfies your request.
you're welcome to add cmake files for Blood2 and submit a PR, that they can be included in the builds
